services:
  db: 
    container_name: db
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=notes_db
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    environment:
      - MONGODB_URL=mongodb://db:27017
    ports:
      - 8000:8000
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    environment:
      - API_URL=backend:8000
    ports:
      - 8080:80
    depends_on:
      - backend